### ISSUE TITLE
VRL -> merge function treated as falliable

### ISSUE THREAD

**Issue by nmiculinic** [vectordotdev/vrl#267] opened 2023-06-16 15:24 UTC
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I have the following VRL:

```
# Parse common formats if possible
structured, err =
    parse_json(.message) ??
    parse_logfmt(.message)

if err == null {
    # This is infaillable, seems to be upstream bug https://vector.dev/docs/reference/vrl/functions/#merge
    . = merge(., structured)
}
```

and upon running it get the following error:

```
  error[E103]: unhandled fallible assignment
    ┌─ :8:9
    │
  8 │     . = merge(., structured)
    │     --- ^^^^^^^^^^^^^^^^^^^^
    │     │   │
    │     │   this expression is fallible
    │     │   update the expression to be infallible
    │     or change this to an infallible assignment:
    │     ., err = merge(., structured)
    │
```

I'm not sure what's the recommended pattern to parse logline formats if possible; and merge accordingly. I could do:
```
., _ = merge(., structured)
```

which makes the VRL pass the compiler check, and it's fine when running unit testing

### Version

vector 0.30.0 (x86_64-apple-darwin 38c3f0b 2023-05-22 17:38:48.655488673)

**Comment by jszwedko** [comment] 2023-06-16 17:51
Hi @nmiculinic !

The issue here is that the `merge` function can only merge objects, but, in your program, VRL can't be sure that `structured` is an object since `parse_json` can return other data types (like integers, booleans, strings, etc.).

One way you could resolve this is with something like:

```
# Parse common formats if possible
structured, err =
    parse_json(.message) ??
    parse_logfmt(.message)

if err == null {
  structured, err = object(structured)
  if err == null {
    # This is infaillable, seems to be upstream bug https://vector.dev/docs/reference/vrl/functions/#merge
    . = merge(., structured)
  }
}
```

Function fallibility is dependent on the function knowing the input argument types. You can read more about this here: https://vector.dev/docs/reference/vrl/expressions/#function-call-characteristics

Hope this helps! Let me know if you have any questions. I'll close this since it is expected behavior albeit could be made more clear.

**Closed by jszwedko** 2023-06-16 17:51 UTC
Labels: type: bug
