### ISSUE TITLE
parse_regex do not accept to_regex(...) pattern argument 

### ISSUE THREAD

**Issue by sxkote** [vectordotdev/vrl#603] opened 2023-12-20 12:26 UTC
That code works fine, because, the pattern is regex expression:
`.res = parse_regex(.message, r'.*program') ?? "not found"`

but if i want to use some expression within the pattern is causes multiple errors:
`.res = parse_regex(.message, to_regex(".*program") ?? r'') ?? "not found"`

error: unexpected expression for argument "pattern"
  │        expected: regex
  │        received: operation

for comparison, the same expression will work in match function

**Comment by jszwedko** [comment] 2023-12-20 14:40
Hi @sxkote !

I think this is a duplicate of https://github.com/vectordotdev/vrl/issues/187. I'll close this out, but feel free to subscribe to that issue for updates.

**Closed by jszwedko** 2023-12-20 14:40 UTC
